"""Batch upload, staging, execution, and summaries for plasmid ONT runs."""

from __future__ import annotations

import csv
import io
import json
import re
import shutil
import subprocess
import uuid
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path, PurePosixPath
from typing import BinaryIO, Callable, Sequence

from .results import parse_flagstat, parse_vcf_variants, read_depth
from .sequences import SequenceRecord, parse_single_sequence, sanitize_name, write_fasta


BARCODE_RE = re.compile(r"^barcode0*([0-9]+)$", re.IGNORECASE)
FASTQ_SUFFIXES = (".fastq", ".fq", ".fastq.gz", ".fq.gz", ".gz")


class BatchPreparationError(ValueError):
    pass


class BatchExecutionError(RuntimeError):
    pass


@dataclass(frozen=True)
class BatchSettings:
    experiment_name: str
    threads: int = 8
    parallel_jobs: int = 16
    min_read_length: int = 500
    min_read_quality: int = 10


@dataclass(frozen=True)
class BatchJob:
    job_dir: Path
    config_path: Path
    manifest_path: Path
    experiment_name: str
    sample_count: int


def natural_key(value: str) -> tuple[object, ...]:
    return tuple(
        int(part) if part.isdigit() else part.casefold()
        for part in re.split(r"(\d+)", value)
    )


def normalize_barcode(value: str) -> str | None:
    match = BARCODE_RE.match((value or "").strip())
    if not match:
        return None
    return f"barcode{int(match.group(1)):02d}"


def barcode_from_upload_name(value: str) -> str | None:
    normalized = value.replace("\\", "/")
    for part in PurePosixPath(normalized).parts:
        barcode = normalize_barcode(part)
        if barcode:
            return barcode
    match = re.search(r"barcode0*([0-9]+)", Path(normalized).name, re.IGNORECASE)
    return f"barcode{int(match.group(1)):02d}" if match else None


def is_fastq_name(value: str) -> bool:
    return value.lower().endswith(FASTQ_SUFFIXES)


def uploaded_barcodes(files: Sequence[object]) -> dict[str, list[object]]:
    grouped: dict[str, list[object]] = {}
    for uploaded in files:
        name = str(getattr(uploaded, "name", ""))
        if not is_fastq_name(name):
            continue
        barcode = barcode_from_upload_name(name)
        if barcode:
            grouped.setdefault(barcode, []).append(uploaded)
    return dict(sorted(grouped.items(), key=lambda item: natural_key(item[0])))


def parse_uploaded_reference(uploaded: object) -> SequenceRecord:
    name = str(getattr(uploaded, "name", "reference.fasta"))
    try:
        raw = uploaded.getvalue()  # type: ignore[attr-defined]
        text = raw.decode("utf-8-sig")
    except UnicodeDecodeError as exc:
        raise BatchPreparationError(f"{name}: UTF-8 FASTA/plain DNA text is required.") from exc
    except AttributeError as exc:
        raise BatchPreparationError(f"{name}: could not read uploaded reference.") from exc
    return parse_single_sequence(text, default_name=Path(name).stem)


def _safe_upload_path(value: str, fallback: str) -> Path:
    parts = [part for part in PurePosixPath(value.replace("\\", "/")).parts if part not in {"", "."}]
    if not parts or any(part == ".." for part in parts):
        return Path(fallback)
    return Path(*(sanitize_name(part, fallback, max_length=150) for part in parts))


def _copy_upload(uploaded: object, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if hasattr(uploaded, "seek"):
        uploaded.seek(0)  # type: ignore[attr-defined]
    with destination.open("wb") as output:
        shutil.copyfileobj(uploaded, output, length=1024 * 1024)  # type: ignore[arg-type]


def _write_config(path: Path, job: BatchJob, settings: BatchSettings) -> None:
    staged = job.job_dir / "staged"
    values: list[tuple[str, object]] = [
        ("references_dir", str((staged / "references").resolve())),
        ("data_dir", str((staged / "data").resolve())),
        ("results_dir", str((job.job_dir / "results").resolve())),
        ("minimap2_preset", "map-ont"),
        ("threads", max(1, min(64, settings.threads))),
        ("parallel_jobs", max(1, min(64, settings.parallel_jobs))),
        ("min_read_length", max(0, settings.min_read_length)),
        ("min_read_quality", max(0, settings.min_read_quality)),
        ("variant_caller", "bcftools"),
        ("pilon_jar", ""),
        ("pilon_mem", "16G"),
    ]
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# Auto-generated by the ONT batch UI.\n")
        for key, value in values:
            rendered = json.dumps(value) if isinstance(value, str) else str(value)
            handle.write(f"{key}: {rendered}\n")


def prepare_batch_job(
    run_root: Path,
    references: Sequence[object],
    reads: Sequence[object],
    mappings: Sequence[dict[str, object]],
    settings: BatchSettings,
) -> BatchJob:
    if not mappings:
        raise BatchPreparationError("No reference-barcode mapping was provided.")
    experiment = sanitize_name(settings.experiment_name, "ONT_batch")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    job_dir = run_root.resolve() / f"{timestamp}_{experiment}_{uuid.uuid4().hex[:8]}"
    reference_dir = job_dir / "staged" / "references" / experiment
    data_dir = job_dir / "staged" / "data" / experiment
    upload_dir = job_dir / "uploads" / "reads"
    results_dir = job_dir / "results"
    for directory in (reference_dir, data_dir, upload_dir, results_dir):
        directory.mkdir(parents=True, exist_ok=True)

    reference_by_file = {Path(str(getattr(item, "name", ""))).name: item for item in references}
    if len(reference_by_file) != len(references):
        raise BatchPreparationError(
            "Reference file names must be unique, even when they came from different folders."
        )
    grouped_reads = uploaded_barcodes(reads)
    staged_reads: dict[str, list[Path]] = {}
    for barcode, barcode_files in grouped_reads.items():
        for index, uploaded in enumerate(barcode_files, 1):
            original = str(getattr(uploaded, "name", f"reads_{index}.fastq.gz"))
            relative = _safe_upload_path(original, f"reads_{index}.fastq.gz")
            destination = upload_dir / barcode / f"{index:04d}_{relative.name}"
            _copy_upload(uploaded, destination)
            staged_reads.setdefault(barcode, []).append(destination.resolve())

    used_barcodes: set[str] = set()
    used_samples: set[str] = set()
    manifest_samples: list[dict[str, object]] = []
    for row_index, row in enumerate(mappings, 1):
        reference_file = Path(str(row.get("reference", ""))).name
        uploaded_reference = reference_by_file.get(reference_file)
        if uploaded_reference is None:
            raise BatchPreparationError(f"Reference upload not found: {reference_file}")
        record = parse_uploaded_reference(uploaded_reference)
        raw_barcodes = row.get("barcodes", [])
        if not isinstance(raw_barcodes, list) or not raw_barcodes:
            raise BatchPreparationError(f"{reference_file}: assign at least one barcode.")
        for replicate, raw_barcode in enumerate(raw_barcodes, 1):
            barcode = normalize_barcode(str(raw_barcode))
            if not barcode:
                raise BatchPreparationError(f"{reference_file}: invalid barcode '{raw_barcode}'.")
            if barcode in used_barcodes:
                raise BatchPreparationError(f"{barcode} is assigned more than once.")
            if barcode not in staged_reads:
                raise BatchPreparationError(f"No uploaded FASTQ was detected for {barcode}.")
            used_barcodes.add(barcode)
            base = sanitize_name(Path(reference_file).stem, f"reference_{row_index}", max_length=52)
            sample_name = sanitize_name(f"{base}__S{replicate}_{barcode}", max_length=80)
            if sample_name in used_samples:
                raise BatchPreparationError(f"Duplicate output name: {sample_name}")
            used_samples.add(sample_name)
            write_fasta(reference_dir / f"{sample_name}.fasta", SequenceRecord(sample_name, record.sequence))
            sample_data_dir = data_dir / sample_name
            sample_data_dir.mkdir(parents=True, exist_ok=True)
            for index, source in enumerate(staged_reads[barcode], 1):
                destination = sample_data_dir / f"{index:04d}_{source.name}"
                destination.symlink_to(source)
            manifest_samples.append(
                {
                    "reference_file": reference_file,
                    "reference_name": Path(reference_file).stem,
                    "barcode": barcode,
                    "replicate": replicate,
                    "sample_name": sample_name,
                    "reference_length": len(record.sequence),
                }
            )

    config_path = job_dir / "batch_config.yaml"
    manifest_path = job_dir / "batch_manifest.json"
    provisional = BatchJob(job_dir, config_path, manifest_path, experiment, len(manifest_samples))
    _write_config(config_path, provisional, settings)
    manifest_path.write_text(
        json.dumps(
            {"experiment_name": experiment, "samples": manifest_samples},
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    return provisional


def run_batch_job(
    repository_root: Path,
    job: BatchJob,
    on_line: Callable[[str], None] | None = None,
) -> Path:
    log_path = job.job_dir / "pipeline.log"
    command = ["bash", str(repository_root / "run_pipeline.sh"), str(job.config_path)]
    recent: list[str] = []
    with log_path.open("w", encoding="utf-8") as log_handle:
        process = subprocess.Popen(
            command,
            cwd=repository_root,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        assert process.stdout is not None
        for line in process.stdout:
            log_handle.write(line)
            log_handle.flush()
            clean = line.rstrip("\n")
            recent.append(clean)
            recent = recent[-40:]
            if on_line:
                on_line(clean)
        return_code = process.wait()
    if return_code != 0:
        raise BatchExecutionError(
            f"Batch pipeline exited with code {return_code}.\n" + "\n".join(recent)
        )
    return log_path


def collect_batch_results(job: BatchJob) -> dict[str, object]:
    manifest = json.loads(job.manifest_path.read_text(encoding="utf-8"))
    result_roots = sorted(
        [path for path in (job.job_dir / "results").glob(f"{job.experiment_name}_*") if path.is_dir()],
        key=lambda path: path.stat().st_mtime,
    )
    result_root = result_roots[-1] if result_roots else None
    staged_reference_dir = job.job_dir / "staged" / "references" / job.experiment_name
    samples: list[dict[str, object]] = []
    for item in manifest["samples"]:
        sample_name = item["sample_name"]
        sample_dir = result_root / sample_name if result_root else Path("/__missing__")
        flagstat = sample_dir / f"{sample_name}.flagstat.txt"
        depth_file = sample_dir / f"{sample_name}.depth.txt"
        vcf = sample_dir / f"{sample_name}.vcf.gz"
        if not flagstat.is_file() or not depth_file.is_file():
            samples.append(
                {
                    **item,
                    "status": "ERROR",
                    "message": (
                        "Mapping 결과가 생성되지 않았습니다. Pipeline log에서 해당 "
                        "sample의 [SKIP] 또는 error 메시지를 확인하세요."
                    ),
                }
            )
            continue
        mapping = parse_flagstat(flagstat)
        depth, _ = read_depth(depth_file)
        reference_path = staged_reference_dir / f"{sample_name}.fasta"
        reference_text = reference_path.read_text(encoding="utf-8")
        reference = parse_single_sequence(reference_text, default_name=sample_name)
        events = (
            parse_vcf_variants(
                vcf,
                reference_sequence=reference.sequence,
                min_quality=20,
                min_depth=10,
                min_allele_fraction=0.8,
                edge_margin=50,
                circular=True,
            )
            if vcf.is_file()
            else []
        )
        passed = sum(event.status == "PASS" for event in events)
        review = len(events) - passed
        low_qc = (
            mapping.mapping_rate is None
            or mapping.mapping_rate < 0.8
            or depth.coverage_1x < 0.95
            or review > 0
        )
        status = "REVIEW" if low_qc else ("VARIANT" if passed else "CLEAN")
        samples.append(
            {
                **item,
                "status": status,
                "total_reads": mapping.total_reads,
                "mapping_rate": mapping.mapping_rate,
                "mean_depth": depth.mean_depth,
                "coverage_1x": depth.coverage_1x,
                "coverage_10x": depth.coverage_10x,
                "variants": len(events),
                "pass_variants": passed,
                "review_variants": review,
                "snp": sum(event.kind == "SNP" for event in events),
                "insertion": sum(event.kind == "Insertion" for event in events),
                "deletion": sum(event.kind == "Deletion" for event in events),
                "variant_details": [event.as_row() for event in events],
            }
        )

    columns = [
        "Reference", "Sample #", "Barcode", "Sample", "Status", "Total reads",
        "Mapping rate", "Mean depth", "Coverage 1x", "Coverage 10x", "Variants",
        "PASS variants", "REVIEW variants", "SNP", "Insertion", "Deletion",
    ]
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=columns)
    writer.writeheader()
    for sample in samples:
        writer.writerow(
            {
                "Reference": sample.get("reference_name"),
                "Sample #": sample.get("replicate"),
                "Barcode": sample.get("barcode"),
                "Sample": sample.get("sample_name"),
                "Status": sample.get("status"),
                "Total reads": sample.get("total_reads"),
                "Mapping rate": sample.get("mapping_rate"),
                "Mean depth": sample.get("mean_depth"),
                "Coverage 1x": sample.get("coverage_1x"),
                "Coverage 10x": sample.get("coverage_10x"),
                "Variants": sample.get("variants"),
                "PASS variants": sample.get("pass_variants"),
                "REVIEW variants": sample.get("review_variants"),
                "SNP": sample.get("snp"),
                "Insertion": sample.get("insertion"),
                "Deletion": sample.get("deletion"),
            }
        )
    groups: dict[str, list[dict[str, object]]] = {}
    for sample in samples:
        groups.setdefault(str(sample["reference_name"]), []).append(sample)
    return {
        "samples": samples,
        "groups": groups,
        "summary_csv": output.getvalue(),
        "result_root": result_root,
    }
