"""Safe staging and execution wrapper around `run_pipeline.sh`."""

from __future__ import annotations

import json
import shutil
import subprocess
import uuid
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import BinaryIO, Callable, Sequence

from .models import PipelineRunResult
from .sequences import SequenceRecord, sanitize_name, write_fasta


FASTQ_SUFFIXES = (".fastq", ".fq", ".fastq.gz", ".fq.gz", ".gz")


class PipelinePreparationError(ValueError):
    pass


class PipelineExecutionError(RuntimeError):
    pass


@dataclass(frozen=True)
class RawAnalysisSettings:
    experiment_name: str
    sample_name: str
    threads: int = 8
    min_read_length: int = 500
    min_read_quality: int = 10
    variant_caller: str = "bcftools"
    pilon_jar: str = ""
    pilon_mem: str = "16G"
    minimap2_preset: str = "map-ont"


@dataclass(frozen=True)
class PipelineJob:
    job_dir: Path
    config_path: Path
    references_root: Path
    data_root: Path
    results_root: Path
    experiment_name: str
    sample_name: str


def is_fastq_path(path: Path) -> bool:
    lower = path.name.lower()
    return any(lower.endswith(suffix) for suffix in FASTQ_SUFFIXES)


def find_fastq_files(source: Path) -> list[Path]:
    source = source.expanduser().resolve()
    if source.is_file():
        if not is_fastq_path(source):
            raise PipelinePreparationError(f"Not a recognized FASTQ file: {source}")
        return [source]
    if not source.is_dir():
        raise PipelinePreparationError(f"FASTQ path does not exist: {source}")
    files = sorted(path for path in source.rglob("*") if path.is_file() and is_fastq_path(path))
    if not files:
        raise PipelinePreparationError(f"No FASTQ/FASTQ.GZ files found under: {source}")
    return files


def missing_dependencies(settings: RawAnalysisSettings) -> list[str]:
    required = ["bash", "minimap2", "samtools", "bcftools"]
    if settings.min_read_length > 0 or settings.min_read_quality > 0:
        required.append("NanoFilt")
    if settings.variant_caller == "medaka":
        required.append("medaka_haploid_variant")
    if settings.variant_caller == "pilon":
        required.append("java")
        if not settings.pilon_jar or not Path(settings.pilon_jar).expanduser().is_file():
            required.append("pilon_jar file")
    return [item for item in required if item == "pilon_jar file" or shutil.which(item) is None]


def _write_config(path: Path, job: PipelineJob, settings: RawAnalysisSettings) -> None:
    values: list[tuple[str, object]] = [
        ("references_dir", str(job.references_root.resolve())),
        ("data_dir", str(job.data_root.resolve())),
        ("results_dir", str(job.results_root.resolve())),
        ("minimap2_preset", settings.minimap2_preset),
        ("threads", max(1, settings.threads)),
        ("parallel_jobs", 1),
        ("min_read_length", max(0, settings.min_read_length)),
        ("min_read_quality", max(0, settings.min_read_quality)),
        ("variant_caller", settings.variant_caller),
        ("pilon_jar", settings.pilon_jar),
        ("pilon_mem", settings.pilon_mem),
    ]
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# Auto-generated by the local ONT UI.\n")
        for key, value in values:
            if isinstance(value, str):
                rendered = json.dumps(value)
            else:
                rendered = str(value)
            handle.write(f"{key}: {rendered}\n")


def prepare_job(
    run_root: Path,
    reference: SequenceRecord,
    settings: RawAnalysisSettings,
    read_paths: Sequence[Path] = (),
    uploaded_reads: Sequence[tuple[str, BinaryIO]] = (),
) -> PipelineJob:
    """Create an isolated job and stage reads without copying server files."""

    experiment = sanitize_name(settings.experiment_name, "experiment")
    sample = sanitize_name(settings.sample_name or reference.name, "sample")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    job_dir = run_root.resolve() / f"{timestamp}_{experiment}_{uuid.uuid4().hex[:8]}"
    references_root = job_dir / "references"
    data_root = job_dir / "data"
    results_root = job_dir / "results"
    reference_dir = references_root / experiment
    sample_data_dir = data_root / experiment / sample
    upload_dir = job_dir / "uploads"
    for directory in (reference_dir, sample_data_dir, results_root, upload_dir):
        directory.mkdir(parents=True, exist_ok=True)

    normalized_reference = SequenceRecord(sample, reference.sequence)
    write_fasta(reference_dir / f"{sample}.fasta", normalized_reference)

    sources = [Path(path).expanduser().resolve() for path in read_paths]
    for path in sources:
        if not path.is_file() or not is_fastq_path(path):
            raise PipelinePreparationError(f"Invalid FASTQ input: {path}")

    for index, (original_name, stream) in enumerate(uploaded_reads, 1):
        safe_name = sanitize_name(Path(original_name).name, f"uploaded_{index}.fastq.gz")
        destination = upload_dir / f"{index:04d}_{safe_name}"
        if not is_fastq_path(destination):
            raise PipelinePreparationError(f"Not a recognized FASTQ upload: {original_name}")
        if hasattr(stream, "seek"):
            stream.seek(0)
        with destination.open("wb") as output:
            shutil.copyfileobj(stream, output, length=1024 * 1024)
        sources.append(destination.resolve())

    if not sources:
        raise PipelinePreparationError("At least one FASTQ/FASTQ.GZ input is required.")

    for index, source in enumerate(sources, 1):
        link_name = sample_data_dir / f"{index:04d}_{source.name}"
        try:
            link_name.symlink_to(source)
        except OSError as exc:
            raise PipelinePreparationError(
                f"Could not stage FASTQ with a symbolic link: {source} ({exc})"
            ) from exc

    job = PipelineJob(
        job_dir=job_dir,
        config_path=job_dir / "config.yaml",
        references_root=references_root,
        data_root=data_root,
        results_root=results_root,
        experiment_name=experiment,
        sample_name=sample,
    )
    _write_config(job.config_path, job, settings)
    return job


def run_job(
    repository_root: Path,
    job: PipelineJob,
    on_line: Callable[[str], None] | None = None,
) -> PipelineRunResult:
    script = repository_root.resolve() / "run_pipeline.sh"
    if not script.is_file():
        raise PipelineExecutionError(f"Pipeline script not found: {script}")
    log_path = job.job_dir / "pipeline.log"
    command = ["bash", str(script), str(job.config_path)]
    recent_lines: list[str] = []
    with log_path.open("w", encoding="utf-8") as log_handle:
        process = subprocess.Popen(
            command,
            cwd=repository_root,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        assert process.stdout is not None
        for line in process.stdout:
            log_handle.write(line)
            log_handle.flush()
            clean = line.rstrip("\n")
            recent_lines.append(clean)
            recent_lines = recent_lines[-30:]
            if on_line:
                on_line(clean)
        return_code = process.wait()

    result_dirs = sorted(
        (path for path in job.results_root.glob(f"{job.experiment_name}_*") if path.is_dir()),
        key=lambda path: path.stat().st_mtime,
    )
    result_dir = result_dirs[-1] if result_dirs else None
    sample_dir = result_dir / job.sample_name if result_dir else None
    expected_bam = sample_dir / f"{job.sample_name}.sorted.bam" if sample_dir else None
    if return_code != 0 or not expected_bam or not expected_bam.is_file():
        detail = "\n".join(recent_lines) or "No pipeline output was captured."
        raise PipelineExecutionError(
            f"ONT pipeline did not complete successfully (exit {return_code}).\n{detail}"
        )

    return PipelineRunResult(
        job_dir=job.job_dir,
        result_dir=result_dir,
        sample_dir=sample_dir,
        sample_name=job.sample_name,
        log_path=log_path,
    )
